version: 0.0
os: linux
files:
  - source: /target/cmy-0.0.1-SNAPSHOT.war
    destination: /tmp
hooks:
  AfterInstall:
    - location: scripts/move_files.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
